---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgB8QuPEFGORiDKszsrkgEpSltGbKj4lMYdrpkJTdzOYh/pQZgIMq48F2S71OSpV84LrmnNQdawiQoxhXqXrNMqfcbzb1RZ6fWUASXQwyyOYw8n2q+nzfcH00haHxGzzz0tzkVUo8Kihw/ZrEmxZJ0kKOxFbEzYk7y3n3HGSL1th8v+GzCUJRhXSu0sMpT4K0HUZxw8bfk392CarrE191z2iM5QXaSAmGFPzmV+q60NzVodvQJfhmcDAPZCM8G9DBu6pn6UxkiT+7bBvnf8kSFMKAsRnTfLB9kEWmyUXtg05uJoLAddiG8lRY83eYPKI0uSEu87Y1/s7QXmSvVy5BET748JX6DyoMmPo7JIZ211rRzVKwRq9dvzxOqW6h9iYGavpKhyDfMAyvYoTjRipsYVeV6E5f3QrfS+lA6uhe+6VSrBtEokoQ5I9KIeiw+6Iod4OoMssX65t8W6xU1lgYLVJuekhqs2bKH5qWAqChLHYhnds1FkhBM9I2tfaxd1Pk2SqxUB6q+f22K1hsxYSRCgClIqGnsDsDjQQW0JXb1ujGau6fbhlOlTKprJiu56Tqe57K9RyZRZuBMN9IV5+9+VbclQCGWcgIXK6tsOj72WSvZPfx2MgNLDGJLC7UQsvcU9PE5DETgDLeeowrqEIHPtpIZz97RWr1XNXiMDlUiIXPQgpEBnszv/HHQFe6BwinCOHPy/skAn5R/bL1FcY51lISFp9a5XIRUbLgVIR5Vc5SQ==
    admin-user: AgB6IsvIQN57RqHRIlsrqtuEeNj6E81kYAa796MsYjfC669qXf4EJDfNgmpZzmoWe+zpTNnqRnGu5H0oueQ7KYjbHObgRWGzG82+NOikT6mN6QeCJD12mw+ct0IFkwvKD/Lw8qBzq9HaH2xvVCK8n3j8fVXDjS89ZoUkI1Mfq5YcARiAvBX8NSFf/sbuX0Yk5XddgfSnGfU1inNpagFU5HSadk92Wk7XSPktXo9IUgEOAFvJdYSCStNGmNoJoFVD+41urpqQf0u8neZ9O8Y7lQkZ1OIvDs8ZMvhgskI1HclMBTJTN5g0T3RP0H1c94xYZwfC249LJR6AHGsH9gHlqPJg3IMOcQbnQnlF2PwJo2eWdJfvdW5/YRZOvslfsTTlvsyvV6LBoTAi0mecJK+2yhNoaBmUBZSAFT5fg+nJwskbf3igQnIHMriQ0P/Zjf79TTuj3L/giN/iUpYiIdxoUG+PneYqn6m9/TPPotm6ee4fe1YW4LmwrfEAuGdov2L7dxR/u9wQlP1qEJNTG6+e2ncIkcXsAi0Qqg8gIwYY9nl3K9hq0EKdvn9Xu1C+noUsmeSkTZtVxcm+tWqAh3GDlonoQ7q/BQrQW5jfhonwKIi10LSY2KfHdDQQ6IX+9poOLOYEUbp85pgtl5Ff+2qP4q7Sipio3mc4nhUrV0WnysiPsOsfCDywrqtPOMpQ23qr3lsB74cOkw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
