---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-ntfy
  namespace: monitoring
spec:
  encryptedData:
    url: AgAOngnKPnlPfE7H48YiTnS2Ql5b13QG1WFjO5bUCykQ0LGWME+EA552CAV7f6+1yBRgWj9Wb9Rpd9P32LzPTwcjluOjquOo3oblyj2u6ms2WRX1Nu1RnhYEvcqR3RaCY0oi2GYwi1vFLv/imw4XGVNZc/prPWy2OLUKDsLV9GL2ZR8jlWGHIxlrZhr/aX70X18uNPZIFM5F+IBtpOA5LTldY737okTgHGzQN0ApHTXY6bPgvxeWr8epz2QWzBHOHjZwJya4LkMDSwFE4EYhxv7oooCNj+cT+wR+4RiJR3NQ/UsQCbbg7aQjC8XmkYyt1YMOJLYKHEFrLhsAbrqDkTee5zRnYKkg8iufcaSxz66A5815qT2ob5mdygIi1Gih2CefwK9PClbRUGYuzyokscV/fmdwStgMlOWD0TCDrEpdlVLFn6++PBmkPfSqnNBvW0kQKGv8d3FwM/rlu0kddNqyBrVFhv8PhJbvIEaShe36h5zJgYkKIfsrLbkjpvEpHPW2QUpxpogXO2CEDOnXkP7DMdG4Z5Ib3jXcwDVbl/jTyle2Cg4QqdkdUh4nFh5FTGFY5MbirZT+is8e2v2ta30K6Lq+0FIsW9Deqj2hZXFh+apoutrQWC2MhUPrLGQdNEaXJ7ya+ENAQzduXW/qRmK/k1W3Ci4sTV2HTrRVGz47gN73m/qCOqQ+FTvZuI+58kzzx8ZpC73BdeDQXIHJM5EewekgNSRdW6FadshZuLXSwtDry7hccSDLkUxm5XV9PdM=
  template:
    metadata:
      name: alertmanager-ntfy
      namespace: monitoring
