---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  encryptedData:
    monitoring-passcode: AgA646C4LaPCwaTRRqrPBRf2wtE3Git7PTC17iyDy3U2IgS/j+sLHtUaDjy5C1jEIrNwWTD5Dv2KiX40upcfk+YbEQSQvnyUko+w4TGz24E28Jp29BFvYyTh1hWlGuG9DHzcMgXnd0ap1ZTOkW1FRfSBlLnYIZwI5IdqPgiyLWxrsV9rx2Rr9dkXKIneU4/+LqvWXRp1KGJ+/ADExDx0rnX0eS9dLCAMMRSNHcXjCevoDkVcWb115TwP9vWDgAHhqy88hc4Fmli5BM+4/uW4FfW+InumgPJimRF82Hra9u2A845Vr15HIa88RnM/4L3hu5+a0ZCGSBtxDGIPXiUHP5419UerRo0+jhN6f6tqNH7/iWTsLqfIrj7hAdepQbSuDt3DwsLcnLtRXk01vxpChVGq1sV8XGuYPiwGeqLZwo/y3ybKG+/ZLQ5t7j8lXQaaHHfFI3TFci3/IKzoHR/1622uK+zzdiuj3lpz9B+WZLtQ6zinnI6x+eUZveo/uR9IwZaS3qBnZGE/MLDBqmm+8TNeo2yfV5s47OI4TAUiQC7+Gwvl7Ge4SZel6UBxIBiqQAZX4a6G/wQRQIjMhBnoB0TfT+9rlYVkq1AA9jwQJaU3spFUAxFKVb68wQmXbEd8LvvvqtOsPA32UtQxDAMt3+5hanU0wmqV7lCeLSXLpT19MV+CxHAR9gprUQYkf0e7WNTO9d4HLy6NACxW3L4LdE0G7WlY8OptFyNux6a6+r/8lQ==
    postgres-password: AgBJCpt+DEsWOuF/nibbh4pofWBllvHaQbccoJ7tNEs78BPjTxP4OcHP1SmN1AWgBgCWpC/3WgY5D8i4u2fd4orS9DK/YA2YX0LaKu7RbyWmC/DorbPRhXAidCY+O3kSU/1ypabN4azPhar4wQ1Q0X3STA9dX+uJXIc6OTBoU1ivJy9vPDs89faaWfodJBt3CSznpWXLl52s5JwUSKoGRSTsYgMzjObAuFDvPbfEN5Rd4k7frBZGOw7Glk3nHH9PFHnZh3t0qwQU4lDfG6yPK78+FRc0uCaffmtB6N4x0Ni8QgJkDFoFL3yWmDH2R1EPPCMDsBamqpQbbP5ScVJ4GYdAL0CQBoLS8gvcYWzL9Rgpavtlu5MmsQaCEvpbBUCxrhCTBsRk+Zvqkw27FS8XzyXZDq/i4kDrv4R74Uz/kA5xuxTv4IcumkWj72msOOx2iAU2dtDI2VdHwUUiqTJXuWlrVIrlSzQWFUzB3sujvcfWT6qvmeyHVPUzGm3P5sPKRntS5HUSnpMdcKZXc87/JTMTjKXWGCGN6uB8zRSx48gfmgkIXAIMHLYibEbzFpWJQEi5R4BcIFmPNhyoVCyNXEG44LO2SodZBO0ywO+1yUIqiUBlYbe3EMSQtIdw82fGCJbuaEFed2cCV299lzjVXvo8nLeCofNp0lpd8lK8UguplWualowQxZBck9ehy7E5ltZ2LAVzirTrcWhujtyOez1Pv6f/JwtYl9ZLtvcz9WseKw==
  template:
    metadata:
      name: sonarqube
      namespace: sonarqube
