---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr
  namespace: revealroll
spec:
  encryptedData:
    .dockerconfigjson: AgAc5D8NBE7SER/5bu5rLHEFU0ReK6vnZxOE9DtmbcTa+XEP7QRYro8INKQEK9/SV11SOKkOIEbCiVrr2KHJ4eQQHTC9U8KQbilTLAarIq91W05OLhSvE+jAlPXC1gypKmC8vtepcpDGqmmjx67HgepHPx/aBD6SBEhZHuRZuxu+VJuAoQs0iLFmLpB1YNvALoakPqpm75bGkMr9Z/HjqaoDnWcXzPlJRervoTQLcdyO2Z+Nu26jKdaAgGni4BcSHOSfm+g99SGCxhs5VyvteZSw5Ven4+De8DSkVBm6bSic37tDEvc6ytxgoEHz0RcVTVMSloRornAj2WXP22Hwu+hL8ZF4IyFzaCl0f8QkBjIPYUDD+U3UMQkwStvaMjwm1rfat5M4lUmtaProxxOlh5lHAe0C853wsg4Wi8zWyp6QqnHSL4sCgna7KxtO8qiZpOIjnFfw1sYe4m0BAV5DRfx6p4tRLlVvNxMb2BFTlG6qlh/QoS1m3g/+jp8hFcG8PM7sopO0pyTgGpEOpXG9Rf/Qx1WUUgsvbIVIcHTz+rxbZHGlOM7hN3fInHuH4lZ3SxEqoRANu84CCV5J/RvfmpfNp/u+lxGbYG6QYlWeWkTR4CoKLQgPzB9xKZFd0/0vjKJ4qByjkiczbXue9badrtiOyclgSzTEyyVM4vJI/68PGbF9M+NG0MXk3aVdN99pJBPjVf+SBjQrOaWP0Rbz88K2ZvGGCsCoHj8mu2t53VUdr5rf94Q8n7td3GM2QZv7PEpwBImGsNtZCIQQIOLD0uQ5Vw90xPqifRJz81BOXR39JTIgWYdZrPBdLMscSNjdRbIwqmoy6Ga8nDR9st4a3utEW2J1JoJhRGbYZFQhlG/KghZGxLv3CR8Esp8xjAO9u775knVXojBX11YXHxulr6SfcvdtM41wKFPmNQ==
  template:
    metadata:
      name: ghcr
      namespace: revealroll
    type: kubernetes.io/dockerconfigjson
