apiVersion: v1
kind: Service
metadata:
  name: {{ include "social-media-host.fullname" . }}
  labels:
    {{- include "social-media-host.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "social-media-host.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
